<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <Keywords>
        <Keyword>dgnFile;Open;Create</Keyword>
      </Keywords>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>DgnModel Load By Id</Title>
      <Author>innovoCAD</Author>
      <Description>Load DgnModel. DgnFile object must be created and loaded prior to this snippet.</Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>MSCEDgnModelLoadById</Shortcut>
    </Header>
    <Snippet>
      <References>
        <Reference>
          <Assembly>Bentley.DgnPlatformNET</Assembly>
        </Reference>
      </References>
      <Imports>
        <Import>
          <Namespace>BDPN = Bentley.DgnPlatformNET</Namespace>
        </Import>
      </Imports>
      <Declarations>
      </Declarations>
      <Code Language="vb" Kind="method body" Delimiter="$"><![CDATA[
'DgnFile object must be created and loaded prior to this snippet.
Dim dgnModelStatus As BDPN.StatusInt
Dim dgnModel As BDPN.DgnModel = dgnFile.LoadRootModelById(dgnModelStatus, modelId)
If dgnModelStatus = BDPN.StatusInt.Success Then
    'TODO: Add code here for successfully loaded dgnModel.
    $end$
End If]]></Code>
    </Snippet>
  </CodeSnippet>
</CodeSnippets>