<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <Keywords>
        <Keyword>dgnFile;Open;Create</Keyword>
      </Keywords>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>ElementProcessor</Title>
      <Author>innovoCAD</Author>
      <Description>Process elements from scan criteria.</Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>MSCEElementProcessor</Shortcut>
    </Header>
    <Snippet>
      <References>
        <Reference>
          <Assembly>Bentley.DgnPlatformNET</Assembly>
        </Reference>
      </References>
      <Imports>
        <Import>
          <Namespace>BDPN = Bentley.DgnPlatformNET</Namespace>
        </Import>
      </Imports>
      <Declarations>
      </Declarations>
      <Code Language="vb" Kind="method decl" Delimiter="$"><![CDATA[''' <summary>
''' Process elements using scan criteria.
''' </summary>
''' <param name="element"></param>
''' <param name="modelRef"></param>
''' <returns></returns>
Public Function ElementProcessor(element As BDPN.Elements.Element, modelRef As BDPN.DgnModelRef) As BDPN.StatusInt
    'TODO: Add code here.

	Return BDPN.StatusInt.Success
End Function]]></Code>
    </Snippet>
  </CodeSnippet>
</CodeSnippets>