<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <Keywords>
        <Keyword>dgnFile;Open;Create</Keyword>
      </Keywords>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>Scan Criteria</Title>
      <Author>innovoCAD</Author>
      <Description>Access elements that match definable criteria from a DgnModel.</Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>MSCEScanCriteria</Shortcut>
    </Header>
    <Snippet>
      <References>
        <Reference>
          <Assembly>Bentley.DgnPlatformNET</Assembly>
        </Reference>
      </References>
      <Imports>
        <Import>
          <Namespace>BDPN = Bentley.DgnPlatformNET</Namespace>
        </Import>
      </Imports>
      <Declarations>
      </Declarations>
      <Code Language="vb" Kind="method body" Delimiter="$"><![CDATA[
'Access elements that match definable criteria from a DgnModel. Use with Element Processor (MSCEElementProcessor Method) and ScanCriteriaExtension.cs project item.
Dim scanCriteria As New BDPN.ScanCriteria()
Dim activeDgnModel As BDPN.DgnModel = BM.Session.Instance.GetActiveDgnModel()
scanCriteria.SetDrawnElements()
scanCriteria.SetModelRef(dgnModel)
Dim msElementTypes As BDPN.MSElementType() = New BDPN.MSElementType() {BDPN.MSElementType.Line}

''' <remarks>Call the extension method defined in ScanCriteriaExtensions.cs</remarks>
scanCriteria.AddElementTypes(msElementTypes)
scanCriteria.Scan(AddressOf ElementProcessor)]]></Code>
    </Snippet>
  </CodeSnippet>
</CodeSnippets>