<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
  <CodeSnippet Format="1.0.0">
    <Header>
      <Keywords>
        <Keyword>dgnFile;Open;Create</Keyword>
      </Keywords>
      <SnippetTypes>
        <SnippetType>Expansion</SnippetType>
      </SnippetTypes>
      <Title>Set Active Color</Title>
      <Author>innovoCAD</Author>
      <Description>Set Active Color.</Description>
      <HelpUrl>
      </HelpUrl>
      <Shortcut>MSCESetActiveColor</Shortcut>
    </Header>
    <Snippet>
      <References>
        <Reference>
          <Assembly>Bentley.DgnPlatformNET</Assembly>
        </Reference>
        <Reference>
          <Assembly>System.Drawing</Assembly>
        </Reference>
      </References>
      <Imports>
        <Import>
          <Namespace>BDPN = Bentley.DgnPlatformNET</Namespace>
        </Import>
        <Import>
          <Namespace>System.Drawing</Namespace>
        </Import>
      </Imports>
      <Declarations>
      </Declarations>
      <Code Language="vb" Kind="method body" Delimiter="$"><![CDATA[Dim elementColor As BDPN.ElementColor = New BDPN.ElementColor(BDPN.ColorSupports.Rgb)
elementColor.Rgb = System.Drawing.Color.Blue
BM.Settings.SetActiveColor(elementColor)]]></Code>
    </Snippet>
  </CodeSnippet>
</CodeSnippets>